-- Generated from generator/demo_specs/aws-philippines-retail-marketplace.json
-- Regenerate with: python3 generator/gen_repo_docs.py aws-philippines-retail-marketplace
-- This is the schema that is actually deployed for PH_RETAIL_MARKETPLACE.

-- Alerts fire on the bottom tail of Buyer Conversion
-- (lower is worse for this metric).
CREATE OR REPLACE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH thresh AS (
  SELECT PERCENTILE_CONT(0.09) WITHIN GROUP (ORDER BY KPI_BUYER_CONVERSION) AS T
  FROM RAW.ORDERS
)
SELECT
  e.ID AS ENTITY_ID,
  e.NAME AS ENTITY_NAME,
  e.REGION,
  e.CATEGORY,
  e.STATUS,
  COUNT(*) AS EVENT_COUNT,
  SUM(CASE WHEN f.KPI_BUYER_CONVERSION <= (SELECT T FROM thresh) THEN 1 ELSE 0 END) AS ALERT_COUNT,
  ROUND(AVG(f.KPI_BUYER_CONVERSION), 2) AS AVG_BUYER_CONVERSION,
  ROUND(AVG(f.KPI_AVG_ORDER_VALUE), 2) AS AVG_ORDER_VALUE,
  ROUND(AVG(f.KPI_REPEAT_PURCHASE), 2) AS AVG_REPEAT_PURCHASE,
  ROUND(AVG(f.KPI_CART_ABANDONMENT), 2) AS AVG_CART_ABANDONMENT
FROM RAW.ORDERS f
JOIN RAW.SELLERS e ON e.ID = f.ENTITY_ID
CROSS JOIN thresh
GROUP BY e.ID, e.NAME, e.REGION, e.CATEGORY, e.STATUS;

CREATE OR REPLACE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT
  f.EVENT_DATE AS METRIC_DATE,
  COUNT(*) AS EVENT_COUNT,
  ROUND(AVG(f.KPI_BUYER_CONVERSION), 2) AS AVG_BUYER_CONVERSION,
  ROUND(AVG(f.KPI_AVG_ORDER_VALUE), 2) AS AVG_ORDER_VALUE,
  ROUND(AVG(f.KPI_REPEAT_PURCHASE), 2) AS AVG_REPEAT_PURCHASE,
  ROUND(AVG(f.KPI_CART_ABANDONMENT), 2) AS AVG_CART_ABANDONMENT
FROM RAW.ORDERS f
GROUP BY f.EVENT_DATE;

-- DISPLAY is rendered here so it is byte-identical to the card the app
-- was designed with (asserted by the round-trip check in kpi_parse.py).
CREATE OR REPLACE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS WITH ev AS (SELECT AVG(KPI_BUYER_CONVERSION) AS KPI_BUYER_CONVERSION, AVG(KPI_AVG_ORDER_VALUE) AS KPI_AVG_ORDER_VALUE, AVG(KPI_REPEAT_PURCHASE) AS KPI_REPEAT_PURCHASE, AVG(KPI_CART_ABANDONMENT) AS KPI_CART_ABANDONMENT FROM RAW.ORDERS),
     en AS (SELECT SUM(KPI_GMV_MTD) AS KPI_GMV_MTD, SUM(KPI_ACTIVE_SELLERS) AS KPI_ACTIVE_SELLERS, SUM(KPI_ORDERS_MTD) AS KPI_ORDERS_MTD FROM RAW.SELLERS)
  SELECT 1 AS SORT_ORDER, 'GMV (MTD)' AS TITLE, KPI_GMV_MTD AS VALUE_NUM, '₱' || TO_VARCHAR(CAST(ROUND(((KPI_GMV_MTD) / 1000000000), 1) AS DECIMAL(38,1))) || 'B' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 2 AS SORT_ORDER, 'Active Sellers' AS TITLE, KPI_ACTIVE_SELLERS AS VALUE_NUM, TO_VARCHAR(CAST(ROUND(((KPI_ACTIVE_SELLERS) / 1000)) AS DECIMAL(38,0))) || 'K' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 3 AS SORT_ORDER, 'Buyer Conversion' AS TITLE, KPI_BUYER_CONVERSION AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_BUYER_CONVERSION), 1) AS DECIMAL(38,1))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 4 AS SORT_ORDER, 'Orders (MTD)' AS TITLE, KPI_ORDERS_MTD AS VALUE_NUM, TO_VARCHAR(CAST(ROUND(((KPI_ORDERS_MTD) / 1000000), 1) AS DECIMAL(38,1))) || 'M' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 5 AS SORT_ORDER, 'Avg Order Value' AS TITLE, KPI_AVG_ORDER_VALUE AS VALUE_NUM, '₱' || TO_VARCHAR(CAST(ROUND((KPI_AVG_ORDER_VALUE)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 6 AS SORT_ORDER, 'Repeat Purchase' AS TITLE, KPI_REPEAT_PURCHASE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_REPEAT_PURCHASE)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 7 AS SORT_ORDER, 'Cart Abandonment' AS TITLE, KPI_CART_ABANDONMENT AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_CART_ABANDONMENT)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
