-- ============================================================================
-- 06_ML_MODELS.SQL — ML Functions for Marketplace Seller Intelligence & Risk Scoring
-- ============================================================================
USE DATABASE MARKETPLACE_INTEL;
USE SCHEMA ML;

-- ML.CLASSIFICATION: SELLER_RISK_CLASSIFIER
CREATE OR REPLACE SNOWFLAKE.ML.CLASSIFICATION ML.SELLER_RISK_CLASSIFIER(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.SELLER_HEALTH_SCORE'),
  TARGET_COLNAME => 'RISK_CATEGORY'
);

-- ML.ANOMALY_DETECTION: SELLER_BEHAVIOR_ANOMALY
CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION ML.SELLER_BEHAVIOR_ANOMALY(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.SELLER_TIMESERIES'),
  SERIES_COLNAME => 'SELLER_ID',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'DAILY_RETURN_RATE',
  LABEL_COLNAME => ''
);

CREATE OR REPLACE TABLE ML.SELLER_BEHAVIOR_ANOMALY_RESULTS AS
SELECT * FROM TABLE(ML.SELLER_BEHAVIOR_ANOMALY!DETECT_ANOMALIES(INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.SELLER_TIMESERIES'), SERIES_COLNAME => 'SELLER_ID', TIMESTAMP_COLNAME => 'DS', TARGET_COLNAME => 'DAILY_RETURN_RATE'));

