-- ============================================================================
-- 99_RESET.SQL — Reset Marketplace Seller Intelligence & Risk Scoring to clean demo state
-- ============================================================================
USE DATABASE MARKETPLACE_INTEL;

-- Suspend tasks during demo
ALTER TASK IF EXISTS APP.TASK_INGEST_METRICS SUSPEND;
ALTER TASK IF EXISTS APP.TASK_SCORE_SELLERS SUSPEND;
ALTER TASK IF EXISTS APP.TASK_DETECT_ANOMALIES SUSPEND;

-- Force refresh Dynamic Tables
ALTER DYNAMIC TABLE CURATED.SELLER_HEALTH_SCORE REFRESH;
ALTER DYNAMIC TABLE CURATED.CATEGORY_RISK_PROFILE REFRESH;
ALTER DYNAMIC TABLE CURATED.SELLER_TIMESERIES REFRESH;
ALTER DYNAMIC TABLE CURATED.MARKETPLACE_GMV REFRESH;

-- Verify key demo numbers
-- SELECT COUNT(*) FROM MARKETPLACE_INTEL.RAW.ORDERS → 4500000
-- SELECT COUNT(*) FROM MARKETPLACE_INTEL.RAW.REVIEWS → 1800000
-- SELECT COUNT(*) FROM MARKETPLACE_INTEL.CURATED.SELLER_HEALTH_SCORE WHERE RISK_CATEGORY = 'HIGH' → ~1240

-- Resume tasks
ALTER TASK IF EXISTS APP.TASK_DETECT_ANOMALIES RESUME;
ALTER TASK IF EXISTS APP.TASK_SCORE_SELLERS RESUME;
ALTER TASK IF EXISTS APP.TASK_INGEST_METRICS RESUME;
